#!/bin/bash
POWERSUPPLY="/sys/bus/acpi/drivers/battery/*/power_supply/BAT0/status"
LOW=20
CRITICAL=10
ICON_OK="/usr/share/icons/Papirus-Dark/16x16/panel/battery-good.svg"
ICON_LOW="/usr/share/icons/Papirus-Dark/16x16/panel/battery-low.svg"
ICON_CRITICAL="/usr/share/icons/Papirus-Dark/16x16/panel/battery-empty.svg"
BATTERY_LEVEL=$(acpi -b | grep -P -o '[0-9]+(?=%)')
STATUS=$(cat $POWERSUPPLY)

if [ $BATTERY_LEVEL -le $CRITICAL -a $STATUS = "Discharging" ]
then
	/usr/bin/notify-send -u critical -i "$ICON_CRITICAL" -t 3000 "Battery critically low" "Battery level is ${BATTERY_LEVEL}%!."

elif [ $BATTERY_LEVEL -le $LOW -a $STATUS = "Discharging" ]
then
	/usr/bin/notify-send -u normal -i "$ICON_LOW" -t 3000 "Battery low" "Battery level is ${BATTERY_LEVEL}%! Please plug in charger now."

#elif [ $BATTERY_LEVEL -ge $LOW ]
#then
#	/usr/bin/notify-send -u low -i "$ICON_OK" -t 3000 "Battery is ok" "Battery level is ${BATTERY_LEVEL}%!"	
fi
exit 0
